### ISSUE TITLE
Change `min_payment` from Uint8 to Uint64

### ISSUE THREAD

**Issue by ashuralyk** [sporeprotocol/spore-contract#43]
# Description
current `min_payment` calculation is `10^x` to match a same implementation in Omnilock and ACP, but since our proxy and mutant cells are located in Celldep field so that there's no need to consider DDos issue, besides, `10^x` would introduce an issue that to be unable with a concrete CKB price for those cells creators.

we can just use a specific CKB price value to indicate this `min_payment` option, which type is Uint64.

**Comment by ashuralyk** [comment]
@Flouse what do you think that we should still keep `min_payment` in `args` or it should be place in `data`?

**Comment by Flouse** [comment]
I think putting min_payment in ClusterProxy's data is more flexible,
because changing min_payment doesn't change type_script_hash.

**Comment by ShookLyngs** [comment]
If I understand correctly, the issue with storing `min_payment` in the type args of ClusterProxy and Mutant is that we cannot query or compare them using their type hash. Instead, we should only query or compare them with their first 32 bytes of the type args, like this:
```rust
cluster_proxy.type_args.as_ref()[..32]
```

From my perspective, the position may not be a significant issue if we can resolve the problem mentioned above. 
However, I have another question: should the min_payment be modifiable? (since ClusterData and SporeData are immutable)

**Comment by Flouse** [comment]
> question: should the min_payment be modifiable? (since ClusterData and SporeData are immutable)

> question: should the min_payment be modifiable? (since ClusterData and SporeData are immutable)

There may be no standard answer to this question.

IMO, the cluster data should be immutable, but the value of a cluster can change over time.

A cluster owner may want to set a low min_payment at the beginning, and increase it later when the cluster is hot or more valuable.
